use_field_init_shorthand = true
use_small_heuristics = "Max"
# Unstable below
unstable_features = true
format_code_in_doc_comments = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_impl_items = true
